### ISSUE TITLE
testfilesの生成コードもcommitして良いのではないか?

### ISSUE THREAD

**Issue by tsuzu** [go-generalize/volcago#12]
api_genはそうなっているが、生成済みコードがcommitされているとレビュー時に生成されたコードの差分も確認することができる
具体的な例を持ってレビューすることができるのでレビューがしやすくなるように感じている

例: 
https://github.com/go-generalize/api_gen/pull/244/files

![Screen Shot 2022-01-06 at 17 07 23](https://user-images.githubusercontent.com/8574909/148350145-8c6c70ac-66ab-413f-87e0-59d5d42e6fad.png)

**Comment by tsuzu** [comment]
@54m 意見求

**Comment by tsuzu** [comment]
## Pros
レビュー時に生成されたコードの差分も確認することができる
具体的な例を持ってレビューすることができるのでレビューがしやすくなるように感じている

## Cons
コード変更に対して差分が大きくなってしまうこと(主な変更点が追いにくい、など)

個人的にはProsの方が大きいと思っている

**Comment by 54m** [comment]
> @54m 意見求

特に意味はなかったと思うので含めてもいいと思います
