### ISSUE TITLE
入れ子構造体の不具合

### ISSUE THREAD

**Issue by 54m** [go-generalize/volcago#5]
```go
type User struct {
	Name string
	Settings *Settings
	Meta
}

type Settings struct {
	Locale string
}
```

みたいな構造体で生成すると↓

![image](https://user-images.githubusercontent.com/30588003/147855104-bcdc1292-7d30-4591-9f7c-6b02b440cf67.png)
![image](https://user-images.githubusercontent.com/30588003/147855116-4ec4237c-d95b-44d1-ae9c-42b8ef181b8e.png)

SettingsにMetaがあることになってしまう

**Comment by 54m** [comment]
@tsuzu 
![image](https://user-images.githubusercontent.com/30588003/148307233-158ee5ba-2c17-408b-b1cf-9b0c859bf7f7.png)
Where句の中で直前のフィールド引きずってる...

v1.1.2

**Comment by 54m** [comment]
![image](https://user-images.githubusercontent.com/30588003/148307554-d8ead0d0-1b3e-4a59-8a89-50101b2a6b9b.png)
そろそろラベリングも見直さないといけないかもしれない

**Comment by tsuzu** [comment]
> ![image](https://user-images.githubusercontent.com/30588003/148307554-d8ead0d0-1b3e-4a59-8a89-50101b2a6b9b.png) そろそろラベリングも見直さないといけないかもしれない(名前をCamelCaseに/期待するのはsではなくl)

これは別issueの方が良さそうですかね
